travis:
  secure:
    BINSTAR_TOKEN: phKE/c3PKcx+5M78hQJbWtRW4ZdVfeNJDlAIJOWvzII7LshzA+HfX70UrOwUsvBUfjmraKxUOmqcqOEQtirYYgk4MdDtE6q/p1qaRGDStBO6ZiKvIbJsyQwFBzseON79rU+tsBBmyj5rdM/+H4rq52DLOBo+MZ3rGwz6KIJyWHEi/UROWuphKKXhgrNCYb1hTebOT4S8Pw4GAL0eTnjrcNB7osC2ZppDVq0uf0Re630d64sQ+AwrX6Da56bUk5ehaDK9fhJfuDBbRUgBV6ohpo5xIZRV/67nnG3hnPmd/v5a1kAXMdfx88xq0jzns8veUdjOXrQZhwzVaCkN4xDFni5zlEitVXe+6BlwnXtZeMS+hMBhLe8cLKxPusk6G6Zux7WjXPyAJusYjQCYoiIX2sHFGHTwOpNVYbJFkGXdTAI44SRBDySzwpVn7aiGxNafo2bIGQcfqvMh4KGjaTCbu0rZ4579FmrpWTTH0yKeCPTD+V6thhcJiXJZgAUvbVR5I2foYz64Nthc4a0zlV2amIGjTNIMDzKukTW/GX3LGE8mP+xRnmoec8aW2zKHxGjMeMr6E67WvY7N++zDDnhXMwbBAn7k5XZFy/0SqSfWQ8L+KzglVSwtwuJ/vt0lVTfqXJLW13qvi+HxmJTThtdjIdSVjrXLi3/goWHOcp+u0vo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
