travis:
  secure:
    BINSTAR_TOKEN: o2d4mcH0jrX6uRCvA2dZRQCZCQ1t6AmKm/xjhvCm7+hesUEcdFz8shY32jOn1DC48CD6rGWZCaO95h/ycEL9zv+XHZkUafDNHzzZMi7oUIIFCoPTXys2cxuqlrN9THbU+5p5zY1ugibf0a1iVbL6Yz07sIs1J17kDf88GAPmre9wR8UWJSFuQXi2oEDjfpb+07XVQPnaddtJL7uZL6BocyaeADnpC8iBP/W2rsoQt94ovRDvxpYoY0LDAbvX4aOfplBHiYtY+HaNY7Psjk6Ofasulm06HaYtlNz2pkyOYxlqwWWrRs0ebiA4+d5oku/SMAHFK/zQkVrsNKCI7y8mekJ1D1IJ+8+QuLcuP3LiqH1wm7NZMPwHPSXoVz7KhjnVA1Lrg72wMZ67j4V6L+dzt57SZ4WQknfay0tYqKotvpOHa8yPAKMqL4x5W1OzsyfrcAWwG36TuH7Yjc58L93Pq9/UivK2eOQvN3KpaT164GdKrd110Xxwr+Uye/6e9wc5K5/lvZQL3Fo6FVm7p0//9pQ/JLArCEHAH80doFKI2EnRugFOj6veCIEDkc4E0Cyj6PEGchLM1La8P8lXn5wUdIa7yJXHQg9BReDzreHgnkQyf9o3VYK5hlSumKZR/1G8yGf1ge2RFGidhwMrp8aZHnLngcD6bW3eq8MFuOhr468=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
